//! `secrets-test-stub` feature の binary と CLI 統合テストが共有する入出力契約名。

pub const SEED_BW_EMAIL_ENV: &str = "DOTFILES_SECRETS_TEST_SEED_BW_EMAIL";
pub const SEED_BW_PASSWORD_ENV: &str = "DOTFILES_SECRETS_TEST_SEED_BW_PASSWORD";
pub const SEED_BWS_ACCESS_TOKEN_ENV: &str = "DOTFILES_SECRETS_TEST_SEED_BWS_ACCESS_TOKEN";
pub const CORRUPT_SECRET_ENV: &str = "DOTFILES_SECRETS_TEST_STUB_CORRUPT_SECRET";
pub const READ_PIN_FROM_TTY_ENV: &str = "DOTFILES_SECRETS_TEST_STUB_READ_PIN_FROM_TTY";
pub const STUB_STATE_ENV: &str = "DOTFILES_SECRETS_TEST_STUB_STATE";
pub const PRIMARY_STUB_STATE_ENV: &str = "DOTFILES_SECRETS_TEST_STUB_PRIMARY_STATE";
pub const SPARE_STUB_STATE_ENV: &str = "DOTFILES_SECRETS_TEST_STUB_SPARE_STATE";
pub const WRITE_EVENT_PREFIX: &str = "dotfiles-secrets-test-stub write";
pub const PRIMARY_SERIAL: u32 = 2001;
pub const SPARE_SERIAL: u32 = 2002;
