[[plugins]]
repo = 'autozimu/LanguageClient-neovim'
rev = 'next'
build = 'bash install.sh'
on_ft = ['ruby', 'reason', 'ocaml', 'python', 'rust']
hook_add = '''
  let g:LanguageClient_serverCommands = {
      \ 'ruby': ['solargraph', 'stdio'],
      \ 'ocaml': ['ocaml-language-server', '--stdio'],
      \ 'python': ['/bin/pyls'],
      \ 'typescript': ['~/.node-bin/javascript-typescript-langserver', '--stdio'],
      \ 'typescript.tsx': ['~/.node-bin/javascript-typescript-langserver', '--stdio'],
      \ 'rust': ['rustup', 'run', 'stable', 'rls']
      \ }
  nnoremap <silent> gd :call LanguageClient_textDocument_definition()<cr>
  nnoremap <silent> gf :call LanguageClient_textDocument_formatting()<cr>
  nnoremap <silent> <cr> :call LanguageClient_textDocument_hover()<cr>
'''

[[plugins]]
repo = 'mattn/emmet-vim'
on_ft = 'html'

[[plugins]]
repo = 'FStarLang/VimFStar'
on_ft = 'fstar'

[[plugins]]
repo  = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = 'pangloss/vim-javascript'
on_ft = ['javascript', 'javascript.jsx']

[[plugins]]
repo = 'mxw/vim-jsx'
on_ft = ['javascript', 'javascript.jsx']

[[plugins]]
repo = 'HerringtonDarkholme/yats.vim'
on_ft = 'typescript'

[[plugins]]
repo = 'digitaltoad/vim-pug'
on_ft = "pug"

[[plugins]]
repo = 'dNitro/vim-pug-complete'
on_ft = "pug"

[[plugins]]
repo = 'posva/vim-vue'
on_ft = 'vue'

[[plugins]]
repo = 'vim-jp/cpp-vim'
on_ft = 'cpp'

[[plugins]]
repo = 'plasticboy/vim-markdown'
on_ft = 'markdown'

[[plugins]]
repo = 'iwataka/minidown.vim'
on_ft = 'markdown'

[[plugins]]
repo = 'hail2u/vim-css3-syntax'
on_ft = 'markdown'

[[plugins]]
repo = 'slim-template/vim-slim'
on_ft = 'slim'

[[plugins]]
repo = 'ocaml/vim-ocaml'
on_ft = 'ocaml'

[[plugins]]
repo = 'artur-shaik/vim-javacomplete2'
hook_post_source = 'autocmd FileType java setlocal omnifunc=javacomplete#Complete'
on_ft = 'ocaml'

[[plugins]]
repo = 'copy/deoplete-ocaml'
on_ft = 'ocaml'
hook_add = '''
  call deoplete#custom#option('ignore_sources', {})
  call deoplete#custom#option('ignore_sources.ocaml', ['buffer', 'around', 'member', 'tag'])
  call deoplete#custom#option('auto_complete_delay', 0)
'''

[[plugins]]
repo = 'rust-lang/rust.vim'
on_ft = 'rust'
hook_add = '''
let g:rustfmt_autosave = 1
'''

[[plugins]]
repo = 'iloginow/vim-stylus'
on_ft = 'stylus'

[[plugins]]
repo = 'rescript-lang/vim-rescript'
on_ft = 'rescript'
hook_post_source = '''
  autocmd BufWritePre <buffer> :RescriptFormat
'''
